### ISSUE TITLE
Decoding ignores relationships in include for compound documents

### ISSUE THREAD

**Issue by abhinandan-isha** [infinum/flutter-plugins-japx#10] opened 2020-12-07 23:57 UTC
[jsonapi-response.txt](https://github.com/infinum/flutter-plugins-japx/files/5655909/jsonapi-response.txt)

japx is not able to parse the relationships in include. In the example file above the user relationship with comments is not decoded. It seems the included parameter support is not sufficient.

**Comment by Dundo7** [comment] 2021-08-31 08:39
Hello, I just removed includeList property from decode function and received this response:

[decoded-response.txt](https://github.com/infinum/flutter-plugins-japx/files/7082420/decoded-response.txt)

Is this what you need? If not, please elaborate the issue further.

**Comment by Dundo7** [comment] 2021-09-02 09:08
If the issue is not resolved with the comment above, feel free to re-open it.

**Closed by Dundo7** 2021-09-02 09:08 UTC
