### ISSUE TITLE
Not parsing included nested sections

### ISSUE THREAD

**Issue by agarwalrohit2503** [infinum/flutter-plugins-japx#26] opened 2023-09-29 09:31 UTC
[json.txt](https://github.com/infinum/flutter-plugins-japx/files/12763139/json.txt)

Have added the json file
Please look into this

**Comment by agarwalrohit2503** [comment] 2023-09-29 09:33
[json.txt](https://github.com/infinum/flutter-plugins-japx/files/12763139/json.txt)

Have added the json file 
Please look into this

**Comment by zenled** [comment] 2024-01-31 12:35
Closing, this is a duplicate of #27

**Closed** 2024-01-31 12:35 UTC
